### ISSUE TITLE
'Calling Points', 'Facilities' tabs do not work in Opera 12.02

### ISSUE THREAD

**Issue by leighman** [poggs/tsdbexplorer#104]
Click (i) button for service
Details page opens showing stations

Click 'Facilities' tab - nothing loads
Try and return to 'Calling points' tab - nothing displays

**Comment by poggs** [comment]
This appears to be a problem with Twitter Bootstrap.  Investigating further.

**Comment by poggs** [comment]
Confirmed as an issue in Bootstrap.  Fixed in the forthcoming 2012-10-01 release.

**Comment by leighman** [comment]
Awesome. Cheers
