### ISSUE TITLE
Vague error when no location matched

### ISSUE THREAD

**Issue by poggs** [poggs/tsdbexplorer#14]
When no matches are found for a location, the vague error:

  "Your searched for FOOBAR, but we couldn't find an exact match."

is shown.  This should say something a little clearer.

(reported by Ralph Chadkirk)

**Comment by swlines** [comment]
There's also a typo with Your for You, in that one.

**Comment by ralphchadkirk** [comment]
Perhaps it could suggest a short list of locations which you might have meant? For example, BKK is not a valid CRS station code, but is similar to BKM - the CRS code for Berkhamsted, so a 'Did you mean BKM?' statement could appear.

Just a thought.

**Comment by poggs** [comment]
Fixed in poggs/tsdbexplorer@197154d2c061409ef8c40666645b1558721ae599.

I will have a think over CRS code fuzzy matching - if you're gonna enter codes, at least enter them correctly ;-)
