### ISSUE TITLE
Searching for an invalid UID

### ISSUE THREAD

**Issue by poggs** [poggs/tsdbexplorer#30]
Searching for an invalid UID results in an error message which is missing the date.

**Comment by ralphchadkirk** [comment]
Just tried reproducing this and I get the date displayed fine. Perhaps intermittent, or has it already been fixed?

**Comment by poggs** [comment]
Looks like I fixed the root cause - I'll do some more digging and close the issue with the commit concerned if so!

**Comment by poggs** [comment]
Can't find where this was fixed
