### ISSUE TITLE
Caching & Home Page Date Fields

### ISSUE THREAD

**Issue by IgnoredAmbience** [poggs/tsdbexplorer#31]
I'm seeing some weirdness with the caching of the form for date/time on the homepage - it's always preselecting Today as 18/1/2012 and the time as 10:26.

A hard-refresh shows Firefox sending the appropriate no-cache headers, but still receives a cached version of the date/time from the server.

Firefox 9.0.1/Arch Linux

**Comment by poggs** [comment]
Fixed in poggs/tsdbexplorer@3b333ac56f917d1b00a29aef2a93354186fbf2d0 which will be deployed in the next 24 hours
