### ISSUE TITLE
Passing trains

### ISSUE THREAD

**Issue by poggs** [poggs/tsdbexplorer#5]
Include an option to show passing trains without going in to Technical mode

**Comment by IgnoredAmbience** [comment]
Is it possible to get search for passing trains at all? My attempts so far are failing.
Eg, http://www.opentraintimes.com/schedule/H52857/2012/1/19 does not appear on searches for KPA

(I'd poke at the code if I didn't have so little time available...)

**Comment by poggs** [comment]
I'm planning to fix this today and roll it in to production later or tomorrow

**Comment by poggs** [comment]
Fixed in poggs/tsdbexplorer@202ce013d34761fa355487eac4b2c219ca5d9c29

**Comment by poggs** [comment]
Times for passing trains don't appear!
