### ISSUE TITLE
Toggle options - low contrast

### ISSUE THREAD

**Issue by poggs** [poggs/tsdbexplorer#51]
There's very low contrast between the highlight for Advanced Mode and the background - maybe put an icon or change the highlight colour?

**Comment by ralphchadkirk** [comment]
Put something on the schedule or search screen saying something along the lines of 'Viewing in advanced mode. <a>Revert to standard mode</a>"?

**Comment by ralphchadkirk** [comment]
This would be solved with Bootstrap 2.0 - the menus change to white with the hover colour of blue.

**Comment by poggs** [comment]
Fixed in poggs/tsdbexplorer@90ad4e62357f42ca296f72ad2c5c01809dd06c0d
