### ISSUE TITLE
Advanced Search by Identity searches today if date is blank

### ISSUE THREAD

**Issue by csogilvie** [poggs/tsdbexplorer#54]
Searching for all scheduled running of the service 7X09 (LUL S-Stock Delivery Service)

Visit http://www.opentraintimes.com/search/identity

The page states: The date field is optional - specify it in the format YYYY-MM-DD and the results will be shown for that day only. Leave it blank, and the entire timetable database will be searched.

I blank the field and get the URL:

http://www.opentraintimes.com/schedule/search?by=train_id&term=7X09&date=

This then gives me:

We couldn't find any trains with the train identity 7X09 running on Tuesday 24th January 2012

However, as 7X09 is scheduled for yesterday and Wednesday this week, so I'd expect it to appear in this case, as the date is blank.

**Comment by csogilvie** [comment]
I know https://github.com/csogilvie/tsdbexplorer/commit/f83f718e17c6d31eb31696b4846cbfa64f813884 appears to fix the issue, but as I'm not a ruby expert, I've no idea if it's the right fix.

**Comment by poggs** [comment]
Fixed in poggs/tsdbexplorer@65dfc456e8a81ffddc637ab5a422224626c91ac7
