### ISSUE TITLE
Civil Engineering trains have 1st and Standard Class Seats

### ISSUE THREAD

**Issue by csogilvie** [poggs/tsdbexplorer#55]
It appears that according to the website, Civil Engineering trains have 1st and Standard Class Seats.

http://www.opentraintimes.com/schedule/B17513/2012/1/26

Not sure whether that's the application or the original data that's causing it though, as I don't have access to Enginering Data locally to test.

**Comment by poggs** [comment]
Engineering trains have the CIF 'train class' field set to space - in the CIF User Specification, space is defined as "1st and Standard Class seats".

A fix would be to only show the seating for passenger schedules, and ignore non-passenger.

**Comment by ralphchadkirk** [comment]
This is shown in the timetable creation software as well - for example ECS services can be shown as being reservable. Usually it's just ignored.

**Comment by poggs** [comment]
Fixed in poggs/tsdbexplorer@f6d84467e778ebdd280a931570dc38e19d0ac759
