### ISSUE TITLE
Starts/terminates here

### ISSUE THREAD

**Issue by swlines** [poggs/tsdbexplorer#59]
Instead of starts/terminates here being in bold, locations should be in bold as otherwise it distracts the eye towards the bits which are irrelevant.

http://www.opentraintimes.com/location/WAT/2012/01/26/19:46

compare with

http://traintimes.im/location/WAT/2012/01/26/9/

**Comment by poggs** [comment]
Fixed in poggs/tsdbexplorer@02ecdbc95d6700f392de9aa7826cd722f5fea404
