### ISSUE TITLE
Advanced search issues with firefox

### ISSUE THREAD

**Issue by ralphchadkirk** [poggs/tsdbexplorer#75]
"I was chasing up Royal Mail trains a couple of days ago and tried to get at the times at the Shieldmuir Terminal (SHILDMT). Even going the Advanced route it wouldn't recognise the TIPLOC (nor the 3 Shieldmuir sigs that have TIPLOC codes, as SHILXXX). I had to go in and out of the site a couple of times and in and out of the Advanced button before it finally picked up the codes from the Advanced route. It then had difficulty with the other RM terminals (Willesden, Warrington, Doncaster and Low Fell) although it picked them all up eventually."
Browser: Firefox Beta 10

Reported by Postal on the SimSig forum.

**Comment by poggs** [comment]
Sounds like a browser-specific problem.  Will try this on Firefox 10 if I can find a beta.

**Comment by ralphchadkirk** [comment]
That's what I thought. I've never had any problems on the latest Safari.

**Comment by poggs** [comment]
Fixed or mitigated in poggs/tsdbexplorer@c74ed348e0190721502cc5198aa1be3741824e71
