### ISSUE TITLE
Allowances

### ISSUE THREAD

**Issue by poggs** [poggs/tsdbexplorer#76]
Move engineering allowances in to square brackets, pathing allowances in to brackets and performance allowances in to angle brackets as per the WTT.

Suggested by Dysgraphyk on uk.railway

**Comment by ralphchadkirk** [comment]
There is a standard that is used in Voyager Plan Rail for the different "types" of time - it sounds very similar to this although I'm pretty sure performance time was <> and angled brackets were hidden time. I could be wrong of course!

If you want to follow that system then I'm happy to contact a train planner to find out what the standard is.

**Comment by ralphchadkirk** [comment]
Sorry, this is me being dense. Angled brackets are of course <>. I was thinking of braces....
