### ISSUE TITLE
Some RoR code displayed to users

### ISSUE THREAD

**Issue by ralphchadkirk** [poggs/tsdbexplorer#82]
I've just searched for the head code 3J11 with no date (http://www.opentraintimes.com/schedule/search?by=train_id&term=3j11&date=) and in the table displayed, I get this in the schedule column:

{:class=>"icon-calendar"}H19008 (WTT) (3J11)    

Furthermore, if I click this schedule, I get this error:
We couldn't find the schedule schedule_by_uid_and_run_date. The schedule may not be valid for this date.

It is the same for all 7 results.

**Comment by poggs** [comment]
Fixed in poggs/tsdbexplorer@dbd2575aa713af7999d7aac72cac3a31858f9c87
