### ISSUE TITLE
CRS code MIR expands to two unrelated TIPLOCs

### ISSUE THREAD

**Issue by poggs** [poggs/tsdbexplorer#91]
"I'm looking at Mirfield http://www.opentraintimes.com/location/MIR/2012/02/20/22:19 and each train appears twice.
I think the reason is that it is giving Mirfield East Junction and Mirfield station on the same page."

It looks like CRS-to-TIPLOC handling in advanced mode is sometimes picking up an unrelated location - may be something to with caching.

Reported by James Fairchild

**Comment by swlines** [comment]
Relates to the MSNF. Mirfield has a 9 that relates to Mirfield East Jn

**Comment by poggs** [comment]
Fixed in poggs/tsdbexplorer@f0e562a0cba00c12f0dbd88dc3706b599c06dd71
